Remove PodMonitor from Namespace level and implement PodMonitor for e…
opendatahub-io/odh-model-controller pull request #126
Opened 2023-12-06 10:50 UTC by vaibhavjainwiz

…ach KServe isvc.

## Description

Currently PodMonitor for KServe isvc is monitoring all pod in the namespace which causes issue in ModelMesh monitor. With this PR I had change the behaviour of PodMonitor to just monitor pods of KServe isvc. It should fix https://github.com/opendatahub-io/odh-model-controller/issues/125

## How Has This Been Tested?

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2023-12-06 10:59 UTC, vaibhavjainwiz commented
Next step is to verify the metrics. With this change both ModelMesh and KServe metrics should be available in Openshift Monitoring stack.

2023-12-06 14:01 UTC, spolti commented on controllers/reconcilers/kserve_istio_podmonitor_reconciler.go
> -	desiredPodMonitor := &v1.PodMonitor{
what is the point of having this function just to return nil?

2023-12-06 14:04 UTC, spolti commented on controllers/reconcilers/kserve_podmonitor_reconciler.go
> +	comparator := comparators.GetPodMonitorComparator()
Don't we have these functions already on the RHSyseng operator-utils?

maybe we could use it from there and avoid each reconciler have its own deltaProcessor.

2023-12-06 14:05 UTC, spolti requested changes
Can you please add a unit test for it?

Just to make sure that the needed resources will be created/update the objects as desired when the reconciler is called.

2023-12-11 14:20 UTC, vaibhavjainwiz commented
Thank you @spolti for reviewing it but I need to close this PR because this solution didn't work. I will raise a new PR to fix this issue on bases of below thread.
https://github.com/opendatahub-io/odh-model-controller/issues/125#issuecomment-1850153594

2023-12-11 14:20 UTC, closed without merging

2023-12-11 14:31 UTC, spolti commented
ok, thanks :)