remove old prometheus clusterrole
opendatahub-io/odh-model-controller pull request #129
Opened 2023-12-08 12:05 UTC by VedantMahabaleshwarkar

## Description

## How Has This Been Tested?

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2024-01-04 05:03 UTC, vaibhavjainwiz requested changes

2024-01-04 05:03 UTC, vaibhavjainwiz commented on controllers/monitoring_controller.go
> +	// log.Info("Monitoring Controller reconciling.")
Complete `monitoring_controller.go` file is resposible for doing `reconcileRoleBinding`. If these reconcilation is not needed anymore then I would suggest to remove this complete controller and all its references.

2024-06-14 13:33 UTC, spolti commented
Do we still need this PR?

2024-10-23 14:14 UTC, spolti commented
closed as stale.

2024-10-23 14:14 UTC, closed without merging